## Batch:Total test data --> True mask and predicted mask pixels -> csv files

Based on saved predicted mask files we are creating csv file : to save the true positive, true negative , false positive and false negative pixel wise scores


In [13]:
# checking mask file contains 0 or 255 binary values
import os
import cv2
import numpy as np
import pandas as pd
true_mask_folder="C:/Users/rajes/OneDrive/Desktop/dataset/results_transdeeplab/best_weights/batch"
image_filenames = os.listdir(true_mask_folder)[:6]
for filename in image_filenames:
    # Load the true mask and predicted mask images
    print(filename)
    true_mask = cv2.imread(os.path.join(true_mask_folder, filename), cv2.IMREAD_GRAYSCALE)
    print(true_mask)

water_body_100_1.png
[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
water_body_100_3.png
[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
water_body_1029_10.png
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
water_body_1037_16.png
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
water_body_1037_31.png
[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
w

In [17]:
import pandas as pd
import os
import cv2
import numpy as np

# Define paths to the true mask and predicted mask folders
true_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/data/test_split/batch/masks"
predicted_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/results_transdeeplab/best_weights/batch"

# Initialize variables to store the counts of true positive, false positive, true negative,
# and false negative water pixels
true_positive_water_pixels = 0
false_positive_water_pixels = 0
true_negative_water_pixels = 0
false_negative_water_pixels = 0

# Create empty lists to store the data for each image
filenames = []
true_water_pixels = []
true_black_pixels = []
predicted_water_pixels = []
predicted_black_pixels = []
true_positive_pixels = []
false_positive_pixels = []
true_negative_pixels = []
false_negative_pixels = []

# Loop through each file in the true mask folder
for filename in os.listdir(true_mask_folder):
    # Load the true and predicted masks
    true_mask = cv2.imread(os.path.join(true_mask_folder, filename), cv2.IMREAD_GRAYSCALE)
    predicted_mask = cv2.imread(os.path.join(predicted_mask_folder, filename), cv2.IMREAD_GRAYSCALE)

    # Count the number of water and black pixels in the true mask
    true_water_pixels_count = np.count_nonzero(true_mask == 255)
    true_black_pixels_count = np.count_nonzero(true_mask == 0)

    # Count the number of water and black pixels in the predicted mask
    predicted_water_pixels_count = np.count_nonzero(predicted_mask == 255)
    predicted_black_pixels_count = np.count_nonzero(predicted_mask == 0)

    # Calculate the number of true positive, false positive, true negative, and false negative
    # water pixels
    for i in range(true_mask.shape[0]):
        for j in range(true_mask.shape[1]):
            if true_mask[i, j] == 255 and predicted_mask[i, j] == 255:
                true_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 255:
                false_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 0:
                true_negative_water_pixels += 1
            elif true_mask[i, j] == 255 and predicted_mask[i, j] == 0:
                false_negative_water_pixels += 1

    # Add the data for this image to the lists
    filenames.append(filename)
    true_water_pixels.append(true_water_pixels_count)
    true_black_pixels.append(true_black_pixels_count)
    predicted_water_pixels.append(predicted_water_pixels_count)
    predicted_black_pixels.append(predicted_black_pixels_count)
    true_positive_pixels.append(true_positive_water_pixels)
    false_positive_pixels.append(false_positive_water_pixels)
    true_negative_pixels.append(true_negative_water_pixels)
    false_negative_pixels.append(false_negative_water_pixels)

    # Reset the variables for the next iteration
    true_positive_water_pixels = 0
    false_positive_water_pixels = 0
    true_negative_water_pixels = 0
    false_negative_water_pixels = 0

# Create a DataFrame to store the data
data = pd.DataFrame({
    "filename": filenames,
    "true_water_pixels": true_water_pixels,
    "true_black_pixels": true_black_pixels,
    "predicted_water_pixels": predicted_water_pixels,
    "predicted_black_pixels": predicted_black_pixels,
    "true_positive_pixels":true_positive_pixels,
    "false_positive_pixels": false_positive_pixels,
    "true_negative_pixels": true_negative_pixels,
    "false_negative_pixels": false_negative_pixels
    })
data.to_csv("C:/Users/rajes/OneDrive/Desktop/dataset/csv_files/transdeeplab/new_batch.csv", index=False)


## batch1:

In [18]:
import pandas as pd
import os
import cv2
import numpy as np

# Define paths to the true mask and predicted mask folders
true_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/data/test_split/batch1/masks"
predicted_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/results_transdeeplab/best_weights/batch1"

# Initialize variables to store the counts of true positive, false positive, true negative,
# and false negative water pixels
true_positive_water_pixels = 0
false_positive_water_pixels = 0
true_negative_water_pixels = 0
false_negative_water_pixels = 0

# Create empty lists to store the data for each image
filenames = []
true_water_pixels = []
true_black_pixels = []
predicted_water_pixels = []
predicted_black_pixels = []
true_positive_pixels = []
false_positive_pixels = []
true_negative_pixels = []
false_negative_pixels = []

# Loop through each file in the true mask folder
for filename in os.listdir(true_mask_folder):
    # Load the true and predicted masks
    true_mask = cv2.imread(os.path.join(true_mask_folder, filename), cv2.IMREAD_GRAYSCALE)
    predicted_mask = cv2.imread(os.path.join(predicted_mask_folder, filename), cv2.IMREAD_GRAYSCALE)

    # Count the number of water and black pixels in the true mask
    true_water_pixels_count = np.count_nonzero(true_mask == 255)
    true_black_pixels_count = np.count_nonzero(true_mask == 0)

    # Count the number of water and black pixels in the predicted mask
    predicted_water_pixels_count = np.count_nonzero(predicted_mask == 255)
    predicted_black_pixels_count = np.count_nonzero(predicted_mask == 0)

    # Calculate the number of true positive, false positive, true negative, and false negative
    # water pixels
    for i in range(true_mask.shape[0]):
        for j in range(true_mask.shape[1]):
            if true_mask[i, j] == 255 and predicted_mask[i, j] == 255:
                true_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 255:
                false_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 0:
                true_negative_water_pixels += 1
            elif true_mask[i, j] == 255 and predicted_mask[i, j] == 0:
                false_negative_water_pixels += 1

    # Add the data for this image to the lists
    filenames.append(filename)
    true_water_pixels.append(true_water_pixels_count)
    true_black_pixels.append(true_black_pixels_count)
    predicted_water_pixels.append(predicted_water_pixels_count)
    predicted_black_pixels.append(predicted_black_pixels_count)
    true_positive_pixels.append(true_positive_water_pixels)
    false_positive_pixels.append(false_positive_water_pixels)
    true_negative_pixels.append(true_negative_water_pixels)
    false_negative_pixels.append(false_negative_water_pixels)

    # Reset the variables for the next iteration
    true_positive_water_pixels = 0
    false_positive_water_pixels = 0
    true_negative_water_pixels = 0
    false_negative_water_pixels = 0

# Create a DataFrame to store the data
data = pd.DataFrame({
    "filename": filenames,
    "true_water_pixels": true_water_pixels,
    "true_black_pixels": true_black_pixels,
    "predicted_water_pixels": predicted_water_pixels,
    "predicted_black_pixels": predicted_black_pixels,
    "true_positive_pixels":true_positive_pixels,
    "false_positive_pixels": false_positive_pixels,
    "true_negative_pixels": true_negative_pixels,
    "false_negative_pixels": false_negative_pixels
    })
data.to_csv("C:/Users/rajes/OneDrive/Desktop/dataset/csv_files/transdeeplab/new_batch1.csv", index=False)

## Batch 2:



In [19]:
import pandas as pd
import os
import cv2
import numpy as np

# Define paths to the true mask and predicted mask folders
true_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/data/test_split/batch2/masks"
predicted_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/results_transdeeplab/best_weights/batch2"

# Initialize variables to store the counts of true positive, false positive, true negative,
# and false negative water pixels
true_positive_water_pixels = 0
false_positive_water_pixels = 0
true_negative_water_pixels = 0
false_negative_water_pixels = 0

# Create empty lists to store the data for each image
filenames = []
true_water_pixels = []
true_black_pixels = []
predicted_water_pixels = []
predicted_black_pixels = []
true_positive_pixels = []
false_positive_pixels = []
true_negative_pixels = []
false_negative_pixels = []

# Loop through each file in the true mask folder
for filename in os.listdir(true_mask_folder):
    # Load the true and predicted masks
    true_mask = cv2.imread(os.path.join(true_mask_folder, filename), cv2.IMREAD_GRAYSCALE)
    predicted_mask = cv2.imread(os.path.join(predicted_mask_folder, filename), cv2.IMREAD_GRAYSCALE)

    # Count the number of water and black pixels in the true mask
    true_water_pixels_count = np.count_nonzero(true_mask == 255)
    true_black_pixels_count = np.count_nonzero(true_mask == 0)

    # Count the number of water and black pixels in the predicted mask
    predicted_water_pixels_count = np.count_nonzero(predicted_mask == 255)
    predicted_black_pixels_count = np.count_nonzero(predicted_mask == 0)

    # Calculate the number of true positive, false positive, true negative, and false negative
    # water pixels
    for i in range(true_mask.shape[0]):
        for j in range(true_mask.shape[1]):
            if true_mask[i, j] == 255 and predicted_mask[i, j] == 255:
                true_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 255:
                false_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 0:
                true_negative_water_pixels += 1
            elif true_mask[i, j] == 255 and predicted_mask[i, j] == 0:
                false_negative_water_pixels += 1

    # Add the data for this image to the lists
    filenames.append(filename)
    true_water_pixels.append(true_water_pixels_count)
    true_black_pixels.append(true_black_pixels_count)
    predicted_water_pixels.append(predicted_water_pixels_count)
    predicted_black_pixels.append(predicted_black_pixels_count)
    true_positive_pixels.append(true_positive_water_pixels)
    false_positive_pixels.append(false_positive_water_pixels)
    true_negative_pixels.append(true_negative_water_pixels)
    false_negative_pixels.append(false_negative_water_pixels)

    # Reset the variables for the next iteration
    true_positive_water_pixels = 0
    false_positive_water_pixels = 0
    true_negative_water_pixels = 0
    false_negative_water_pixels = 0

# Create a DataFrame to store the data
data = pd.DataFrame({
    "filename": filenames,
    "true_water_pixels": true_water_pixels,
    "true_black_pixels": true_black_pixels,
    "predicted_water_pixels": predicted_water_pixels,
    "predicted_black_pixels": predicted_black_pixels,
    "true_positive_pixels":true_positive_pixels,
    "false_positive_pixels": false_positive_pixels,
    "true_negative_pixels": true_negative_pixels,
    "false_negative_pixels": false_negative_pixels
    })
data.to_csv("C:/Users/rajes/OneDrive/Desktop/dataset/csv_files/transdeeplab/new_batch2.csv", index=False)

## batch 3:

In [21]:
import pandas as pd
import os
import cv2
import numpy as np

# Define paths to the true mask and predicted mask folders
true_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/data/test_split/batch3/masks"
predicted_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/results_transdeeplab/best_weights/batch3"

# Initialize variables to store the counts of true positive, false positive, true negative,
# and false negative water pixels
true_positive_water_pixels = 0
false_positive_water_pixels = 0
true_negative_water_pixels = 0
false_negative_water_pixels = 0

# Create empty lists to store the data for each image
filenames = []
true_water_pixels = []
true_black_pixels = []
predicted_water_pixels = []
predicted_black_pixels = []
true_positive_pixels = []
false_positive_pixels = []
true_negative_pixels = []
false_negative_pixels = []

# Loop through each file in the true mask folder
for filename in os.listdir(true_mask_folder):
    # Load the true and predicted masks
    true_mask = cv2.imread(os.path.join(true_mask_folder, filename), cv2.IMREAD_GRAYSCALE)
    predicted_mask = cv2.imread(os.path.join(predicted_mask_folder, filename), cv2.IMREAD_GRAYSCALE)

    # Count the number of water and black pixels in the true mask
    true_water_pixels_count = np.count_nonzero(true_mask == 255)
    true_black_pixels_count = np.count_nonzero(true_mask == 0)

    # Count the number of water and black pixels in the predicted mask
    predicted_water_pixels_count = np.count_nonzero(predicted_mask == 255)
    predicted_black_pixels_count = np.count_nonzero(predicted_mask == 0)

    # Calculate the number of true positive, false positive, true negative, and false negative
    # water pixels
    for i in range(true_mask.shape[0]):
        for j in range(true_mask.shape[1]):
            if true_mask[i, j] == 255 and predicted_mask[i, j] == 255:
                true_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 255:
                false_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 0:
                true_negative_water_pixels += 1
            elif true_mask[i, j] == 255 and predicted_mask[i, j] == 0:
                false_negative_water_pixels += 1

    # Add the data for this image to the lists
    filenames.append(filename)
    true_water_pixels.append(true_water_pixels_count)
    true_black_pixels.append(true_black_pixels_count)
    predicted_water_pixels.append(predicted_water_pixels_count)
    predicted_black_pixels.append(predicted_black_pixels_count)
    true_positive_pixels.append(true_positive_water_pixels)
    false_positive_pixels.append(false_positive_water_pixels)
    true_negative_pixels.append(true_negative_water_pixels)
    false_negative_pixels.append(false_negative_water_pixels)

    # Reset the variables for the next iteration
    true_positive_water_pixels = 0
    false_positive_water_pixels = 0
    true_negative_water_pixels = 0
    false_negative_water_pixels = 0

# Create a DataFrame to store the data
data = pd.DataFrame({
    "filename": filenames,
    "true_water_pixels": true_water_pixels,
    "true_black_pixels": true_black_pixels,
    "predicted_water_pixels": predicted_water_pixels,
    "predicted_black_pixels": predicted_black_pixels,
    "true_positive_pixels":true_positive_pixels,
    "false_positive_pixels": false_positive_pixels,
    "true_negative_pixels": true_negative_pixels,
    "false_negative_pixels": false_negative_pixels
    })
data.to_csv("C:/Users/rajes/OneDrive/Desktop/dataset/csv_files/transdeeplab/new_batch3.csv", index=False)

## Batch 4:

In [22]:
import pandas as pd
import os
import cv2
import numpy as np

# Define paths to the true mask and predicted mask folders
true_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/data/test_split/batch4/masks"
predicted_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/results_transdeeplab/best_weights/batch4"

# Initialize variables to store the counts of true positive, false positive, true negative,
# and false negative water pixels
true_positive_water_pixels = 0
false_positive_water_pixels = 0
true_negative_water_pixels = 0
false_negative_water_pixels = 0

# Create empty lists to store the data for each image
filenames = []
true_water_pixels = []
true_black_pixels = []
predicted_water_pixels = []
predicted_black_pixels = []
true_positive_pixels = []
false_positive_pixels = []
true_negative_pixels = []
false_negative_pixels = []

# Loop through each file in the true mask folder
for filename in os.listdir(true_mask_folder):
    # Load the true and predicted masks
    true_mask = cv2.imread(os.path.join(true_mask_folder, filename), cv2.IMREAD_GRAYSCALE)
    predicted_mask = cv2.imread(os.path.join(predicted_mask_folder, filename), cv2.IMREAD_GRAYSCALE)

    # Count the number of water and black pixels in the true mask
    true_water_pixels_count = np.count_nonzero(true_mask == 255)
    true_black_pixels_count = np.count_nonzero(true_mask == 0)

    # Count the number of water and black pixels in the predicted mask
    predicted_water_pixels_count = np.count_nonzero(predicted_mask == 255)
    predicted_black_pixels_count = np.count_nonzero(predicted_mask == 0)

    # Calculate the number of true positive, false positive, true negative, and false negative
    # water pixels
    for i in range(true_mask.shape[0]):
        for j in range(true_mask.shape[1]):
            if true_mask[i, j] == 255 and predicted_mask[i, j] == 255:
                true_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 255:
                false_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 0:
                true_negative_water_pixels += 1
            elif true_mask[i, j] == 255 and predicted_mask[i, j] == 0:
                false_negative_water_pixels += 1

    # Add the data for this image to the lists
    filenames.append(filename)
    true_water_pixels.append(true_water_pixels_count)
    true_black_pixels.append(true_black_pixels_count)
    predicted_water_pixels.append(predicted_water_pixels_count)
    predicted_black_pixels.append(predicted_black_pixels_count)
    true_positive_pixels.append(true_positive_water_pixels)
    false_positive_pixels.append(false_positive_water_pixels)
    true_negative_pixels.append(true_negative_water_pixels)
    false_negative_pixels.append(false_negative_water_pixels)

    # Reset the variables for the next iteration
    true_positive_water_pixels = 0
    false_positive_water_pixels = 0
    true_negative_water_pixels = 0
    false_negative_water_pixels = 0

# Create a DataFrame to store the data
data = pd.DataFrame({
    "filename": filenames,
    "true_water_pixels": true_water_pixels,
    "true_black_pixels": true_black_pixels,
    "predicted_water_pixels": predicted_water_pixels,
    "predicted_black_pixels": predicted_black_pixels,
    "true_positive_pixels":true_positive_pixels,
    "false_positive_pixels": false_positive_pixels,
    "true_negative_pixels": true_negative_pixels,
    "false_negative_pixels": false_negative_pixels
    })
data.to_csv("C:/Users/rajes/OneDrive/Desktop/dataset/csv_files/transdeeplab/new_batch4.csv", index=False)

## Batch 5:

In [24]:
import pandas as pd
import os
import cv2
import numpy as np

# Define paths to the true mask and predicted mask folders
true_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/data/test_split/batch5/masks"
predicted_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/results_transdeeplab/best_weights/batch5"

# Initialize variables to store the counts of true positive, false positive, true negative,
# and false negative water pixels
true_positive_water_pixels = 0
false_positive_water_pixels = 0
true_negative_water_pixels = 0
false_negative_water_pixels = 0

# Create empty lists to store the data for each image
filenames = []
true_water_pixels = []
true_black_pixels = []
predicted_water_pixels = []
predicted_black_pixels = []
true_positive_pixels = []
false_positive_pixels = []
true_negative_pixels = []
false_negative_pixels = []

# Loop through each file in the true mask folder
for filename in os.listdir(true_mask_folder):
    # Load the true and predicted masks
    true_mask = cv2.imread(os.path.join(true_mask_folder, filename), cv2.IMREAD_GRAYSCALE)
    predicted_mask = cv2.imread(os.path.join(predicted_mask_folder, filename), cv2.IMREAD_GRAYSCALE)

    # Count the number of water and black pixels in the true mask
    true_water_pixels_count = np.count_nonzero(true_mask == 255)
    true_black_pixels_count = np.count_nonzero(true_mask == 0)

    # Count the number of water and black pixels in the predicted mask
    predicted_water_pixels_count = np.count_nonzero(predicted_mask == 255)
    predicted_black_pixels_count = np.count_nonzero(predicted_mask == 0)

    # Calculate the number of true positive, false positive, true negative, and false negative
    # water pixels
    for i in range(true_mask.shape[0]):
        for j in range(true_mask.shape[1]):
            if true_mask[i, j] == 255 and predicted_mask[i, j] == 255:
                true_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 255:
                false_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 0:
                true_negative_water_pixels += 1
            elif true_mask[i, j] == 255 and predicted_mask[i, j] == 0:
                false_negative_water_pixels += 1

    # Add the data for this image to the lists
    filenames.append(filename)
    true_water_pixels.append(true_water_pixels_count)
    true_black_pixels.append(true_black_pixels_count)
    predicted_water_pixels.append(predicted_water_pixels_count)
    predicted_black_pixels.append(predicted_black_pixels_count)
    true_positive_pixels.append(true_positive_water_pixels)
    false_positive_pixels.append(false_positive_water_pixels)
    true_negative_pixels.append(true_negative_water_pixels)
    false_negative_pixels.append(false_negative_water_pixels)

    # Reset the variables for the next iteration
    true_positive_water_pixels = 0
    false_positive_water_pixels = 0
    true_negative_water_pixels = 0
    false_negative_water_pixels = 0

# Create a DataFrame to store the data
data = pd.DataFrame({
    "filename": filenames,
    "true_water_pixels": true_water_pixels,
    "true_black_pixels": true_black_pixels,
    "predicted_water_pixels": predicted_water_pixels,
    "predicted_black_pixels": predicted_black_pixels,
    "true_positive_pixels":true_positive_pixels,
    "false_positive_pixels": false_positive_pixels,
    "true_negative_pixels": true_negative_pixels,
    "false_negative_pixels": false_negative_pixels
    })
data.to_csv("C:/Users/rajes/OneDrive/Desktop/dataset/csv_files/transdeeplab/new_batch5.csv", index=False)

## Batch 6:

In [23]:
import pandas as pd
import os
import cv2
import numpy as np

# Define paths to the true mask and predicted mask folders
true_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/data/test_split/batch6/masks"
predicted_mask_folder = "C:/Users/rajes/OneDrive/Desktop/dataset/results_transdeeplab/best_weights/batch6"

# Initialize variables to store the counts of true positive, false positive, true negative,
# and false negative water pixels
true_positive_water_pixels = 0
false_positive_water_pixels = 0
true_negative_water_pixels = 0
false_negative_water_pixels = 0

# Create empty lists to store the data for each image
filenames = []
true_water_pixels = []
true_black_pixels = []
predicted_water_pixels = []
predicted_black_pixels = []
true_positive_pixels = []
false_positive_pixels = []
true_negative_pixels = []
false_negative_pixels = []

# Loop through each file in the true mask folder
for filename in os.listdir(true_mask_folder):
    # Load the true and predicted masks
    true_mask = cv2.imread(os.path.join(true_mask_folder, filename), cv2.IMREAD_GRAYSCALE)
    predicted_mask = cv2.imread(os.path.join(predicted_mask_folder, filename), cv2.IMREAD_GRAYSCALE)

    # Count the number of water and black pixels in the true mask
    true_water_pixels_count = np.count_nonzero(true_mask == 255)
    true_black_pixels_count = np.count_nonzero(true_mask == 0)

    # Count the number of water and black pixels in the predicted mask
    predicted_water_pixels_count = np.count_nonzero(predicted_mask == 255)
    predicted_black_pixels_count = np.count_nonzero(predicted_mask == 0)

    # Calculate the number of true positive, false positive, true negative, and false negative
    # water pixels
    for i in range(true_mask.shape[0]):
        for j in range(true_mask.shape[1]):
            if true_mask[i, j] == 255 and predicted_mask[i, j] == 255:
                true_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 255:
                false_positive_water_pixels += 1
            elif true_mask[i, j] == 0 and predicted_mask[i, j] == 0:
                true_negative_water_pixels += 1
            elif true_mask[i, j] == 255 and predicted_mask[i, j] == 0:
                false_negative_water_pixels += 1

    # Add the data for this image to the lists
    filenames.append(filename)
    true_water_pixels.append(true_water_pixels_count)
    true_black_pixels.append(true_black_pixels_count)
    predicted_water_pixels.append(predicted_water_pixels_count)
    predicted_black_pixels.append(predicted_black_pixels_count)
    true_positive_pixels.append(true_positive_water_pixels)
    false_positive_pixels.append(false_positive_water_pixels)
    true_negative_pixels.append(true_negative_water_pixels)
    false_negative_pixels.append(false_negative_water_pixels)

    # Reset the variables for the next iteration
    true_positive_water_pixels = 0
    false_positive_water_pixels = 0
    true_negative_water_pixels = 0
    false_negative_water_pixels = 0

# Create a DataFrame to store the data
data = pd.DataFrame({
    "filename": filenames,
    "true_water_pixels": true_water_pixels,
    "true_black_pixels": true_black_pixels,
    "predicted_water_pixels": predicted_water_pixels,
    "predicted_black_pixels": predicted_black_pixels,
    "true_positive_pixels":true_positive_pixels,
    "false_positive_pixels": false_positive_pixels,
    "true_negative_pixels": true_negative_pixels,
    "false_negative_pixels": false_negative_pixels
    })
data.to_csv("C:/Users/rajes/OneDrive/Desktop/dataset/csv_files/transdeeplab/new_batch6.csv", index=False)